Bj pundit authorization
borvux/industrial-auth-1 pull request #2
Opened 2024-07-17 21:30 UTC by borvux

2024-07-22 21:00 UTC, ajmompr requested changes
Fix user policy

2024-07-22 21:00 UTC, ajmompr commented on app/controllers/application_controller.rb
> +  after_action :verify_authorized, unless: :devise_controller?
good job accounting for devise

2024-07-22 21:00 UTC, ajmompr commented on app/controllers/comments_controller.rb
> +  before_action { authorize(@comment || Comment) }
good

2024-07-22 21:00 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
> +  before_action { authorize(@follow_request || FollowRequest) }
good

2024-07-22 21:00 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +  before_action { authorize(@photo || Photo) }
good

2024-07-22 21:00 UTC, ajmompr commented on app/controllers/users_controller.rb
> +  before_action { authorize(@user || User) }
good

2024-07-22 21:00 UTC, ajmompr commented on app/policies/user_policy.rb
show? should be set to true. Move the logic in show to a new show_photo? method to account for displaying the profiles of private vs public feeds

2024-07-22 21:00 UTC, ajmompr commented on app/views/users/show.html.erb
> +<% if policy(@user).show? %>
call your new show_photo? policy method here

2024-07-22 21:37 UTC, reherr approved these changes
looks good to me now!

2024-07-23 17:16 UTC, ajmompr approved these changes

2024-07-23 17:16 UTC, ajmompr commented on app/views/users/show.html.erb
> +<% if policy(@user).show_photos? %>
good

2024-07-23 17:26 UTC, merged